/* Generated By:JavaCC: Do not edit this line. TernParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TernParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QM = 6;
  /** RegularExpression Id. */
  int QOLON = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"?\"",
    "\":\"",
    "<NUMBER>",
  };

}
