//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> <NUMBER>
    * f1 -> [ TernTail() ]
    */
   public void visit(Tern n);

   /**
    * f0 -> "?"
    * f1 -> Tern()
    * f2 -> ":"
    * f3 -> Tern()
    */
   public void visit(TernTail n);

}

